name: Build Vue
on:
  push:
    branches: [ main ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: hotrungnhan/VuePagesAction@1.0.1
      with:
        username: 'fsodano'
        reponame: 'tss-admin'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
